"""empty message

Revision ID: 0e85503337a3
Revises: e30127a304d6
Create Date: 2024-05-04 13:27:31.518403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0e85503337a3'
down_revision: Union[str, None] = 'e30127a304d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('weather', 'city',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('weather', 'description',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('weather', 'temperature',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('weather', 'wind',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('weather', 'weather_when',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('weather', 'humidity',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('weather', 'icon',
               existing_type=mysql.VARCHAR(length=45),
               type_=sa.String(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('weather', 'icon',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=45),
               nullable=True)
    op.alter_column('weather', 'humidity',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('weather', 'weather_when',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('weather', 'wind',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('weather', 'temperature',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('weather', 'description',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('weather', 'city',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
